USE [master]
GO
CREATE DATABASE [EncodedComparer]
GO
USE [EncodedComparer]
GO
CREATE TABLE [dbo].[LeftData](
	[Id] [int] NOT NULL,
	[Base64EncodedData] [varchar](max) NOT NULL,
 CONSTRAINT [PK_LeftData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RightData](
	[Id] [int] NOT NULL,
	[Base64EncodedData] [varchar](max) NOT NULL,
 CONSTRAINT [PK_RightData] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [EncodedComparer] SET  READ_WRITE 
GO
